export type CalculatorKey='dca'|'compare'|'goal'|'fees'|'cagr'|'compound';
export type CalculatorMeta={key:CalculatorKey;slug:string;name:string;title:string;description:string;short:string;intro:string;method:string;formula:string;example:string;assumptions:string[];faqs:{q:string;a:string}[];related:CalculatorKey[]};
const faq=(topic:string)=>[
 {q:`What does this ${topic} show?`,a:'It turns the assumptions you enter into a hypothetical estimate so you can explore long-term scenarios.'},
 {q:'Does this calculator predict investment returns?',a:'No. The return is a constant user-provided assumption; real returns vary and may be negative.'},
 {q:'Are taxes and inflation included?',a:'No. Results are nominal estimates and exclude taxes and inflation unless a calculator explicitly says otherwise.'},
 {q:'When are contributions added?',a:'Recurring contributions are modeled at the end of each selected contribution period.'},
 {q:'Are fees included?',a:'Fees are excluded except in the ETF fee calculator, which models expense ratios using a simplified net-return approach.'},
 {q:'Can I enter a negative return?',a:'Yes, returns greater than -100% are supported to help test downside scenarios.'}
];
export const calculators:CalculatorMeta[]=[
 {key:'dca',slug:'dca-calculator',name:'DCA Calculator',title:'DCA Calculator – Dollar Cost Averaging Investment Calculator',description:'Use this free DCA calculator to estimate how regular monthly investments may grow over time based on your starting amount, contributions, expected return, and investment period.',short:'Estimate how regular monthly contributions may grow over time.',intro:'Estimate how regular investments could grow over time with dollar-cost averaging.',method:'The calculator converts the annual return assumption to an equivalent monthly rate. It compounds the existing balance, then adds each monthly contribution at the end of the month.',formula:'Balanceₙ = Balanceₙ₋₁ × (1 + monthly rate) + monthly contribution',example:'With $10,000 initially, $500 per month, an 8% assumed return, and 20 years, the tool compounds the balance across 240 monthly periods.',assumptions:['Returns remain constant for illustration.','Contributions occur at month-end.','Taxes, fees, and inflation are excluded.'],faqs:faq('DCA calculator'),related:['compare','compound','goal']},
 {key:'compare',slug:'dca-vs-lump-sum-calculator',name:'DCA vs Lump Sum Calculator',title:'DCA vs Lump Sum Calculator – Compare Investment Strategies',description:'Compare the hypothetical results of investing available capital immediately or gradually over a chosen DCA period.',short:'Compare investing capital now with gradually investing it over time.',intro:'Compare two contribution schedules using the same return and time assumptions.',method:'Strategy A compounds all available capital from the first month. Strategy B divides it into equal month-end installments during the DCA period. Both use the same monthly-equivalent return.',formula:'DCA installment = available amount ÷ DCA months',example:'For $20,000 over 12 DCA months and a 10-year horizon, each DCA installment is $1,666.67 while the lump sum begins compounding immediately.',assumptions:['Uninvested DCA cash earns no return.','The same constant return applies each month.','Taxes, trading costs, and volatility are excluded.'],faqs:faq('strategy comparison'),related:['dca','compound','goal']},
 {key:'goal',slug:'investment-goal-calculator',name:'Investment Goal Calculator',title:'Investment Goal Calculator – Calculate Monthly Contributions',description:'Calculate the monthly contribution or estimated time needed to reach a hypothetical investment target.',short:'Estimate a monthly contribution or timeline for an investment target.',intro:'Work backward from a target to estimate a contribution or timeline.',method:'Contribution mode rearranges the future-value-of-an-annuity formula. Time mode simulates monthly compounding until the target is reached, up to 100 years.',formula:'Monthly contribution = (target − current balance growth) ÷ annuity factor',example:'Enter a $25,000 balance, $250,000 target, 15 years, and 7% return to estimate the required month-end contribution.',assumptions:['The target is a nominal future value.','Return stays constant.','Contributions occur monthly at period-end.'],faqs:faq('investment goal calculator'),related:['dca','compound','fees']},
 {key:'fees',slug:'etf-fee-calculator',name:'ETF Fee Calculator',title:'ETF Fee Calculator – Compare Expense Ratio Costs',description:'Compare how two user-entered ETF expense ratios may affect hypothetical long-term investment growth.',short:'Compare the long-term impact of two expense-ratio assumptions.',intro:'See how small differences in annual expense ratios can compound over time.',method:'This simplified model subtracts each expense ratio from the gross return, compounds the resulting net rate monthly, and compares it with a no-fee scenario.',formula:'Assumed net return = gross annual return − expense ratio',example:'Compare 0.03% and 0.25% fees on $10,000 plus $500 monthly over 30 years at an 8% gross return.',assumptions:['Expense ratios and gross returns stay constant.','Tracking difference, taxes, spreads, trading costs, and portfolio changes are excluded.','Fee impact is estimated, not an itemized fee ledger.'],faqs:faq('ETF fee calculator'),related:['compound','goal','dca']},
 {key:'cagr',slug:'cagr-calculator',name:'CAGR Calculator',title:'CAGR Calculator – Compound Annual Growth Rate',description:'Calculate compound annual growth rate, total return, and growth multiple from beginning and ending values.',short:'Convert beginning and ending values into an annualized growth rate.',intro:'Calculate the smoothed annual growth rate between two values.',method:'CAGR finds the constant annual rate that would turn the beginning value into the ending value over the specified number of years.',formula:'CAGR = (Ending Value ÷ Beginning Value)^(1 ÷ Years) − 1',example:'A value that grows from $10,000 to $20,000 over 10 years has a CAGR of about 7.18%.',assumptions:['Beginning value must be above zero.','CAGR smooths volatility and is not an actual year-by-year path.','Cash flows during the period are not included.'],faqs:faq('CAGR calculator'),related:['compound','dca','goal']},
 {key:'compound',slug:'compound-investment-calculator',name:'Compound Investment Calculator',title:'Compound Investment Calculator – Estimate Long-Term Growth',description:'Estimate long-term compound investment growth with flexible contribution and compounding frequencies.',short:'Model recurring contributions with flexible compounding frequencies.',intro:'Explore how recurring investments and compounding frequency affect a hypothetical balance.',method:'At each compounding interval, the existing balance earns the equivalent periodic return. Contributions are then added whenever a contribution date coincides with that timeline.',formula:'Periodic rate = (1 + annual return)^(1 ÷ periods per year) − 1',example:'Model $10,000 initially and $500 monthly for 20 years, comparing monthly, quarterly, or annual compounding.',assumptions:['Rates and contributions remain constant.','Contributions occur at period-end.','Taxes, inflation, and fees are excluded.'],faqs:faq('compound investment calculator'),related:['dca','goal','fees']}
];
export const bySlug=(slug:string)=>calculators.find(c=>c.slug===slug);
export const byKey=(key:CalculatorKey)=>calculators.find(c=>c.key===key)!;
